//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAkzg.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EAkzg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap czekaj {
            get {
                object obj = ResourceManager.GetObject("czekaj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a id=&quot;^@^&quot;&gt;&lt;h1&gt;^@^&lt;/a&gt;&lt;a class=&quot;spisPowrot&quot; href=&quot;#spisTresci&quot;&gt;Powrót do spisu treści &lt;/a&gt;&lt;/h1&gt;.
        /// </summary>
        public static string h1 {
            get {
                return ResourceManager.GetString("h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a id=&quot;^@^&quot;&gt;&lt;h2&gt;^@^&lt;/a&gt;&lt;a class=&quot;spisPowrot&quot; href=&quot;#spisTresci&quot;&gt;Powrót do spisu treści &lt;/a&gt;&lt;/h2&gt;.
        /// </summary>
        public static string h2 {
            get {
                return ResourceManager.GetString("h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a id=&quot;^@^&quot;&gt;&lt;h3&gt;^@^&lt;/a&gt;&lt;a class=&quot;spisPowrot&quot; href=&quot;#spisTresci&quot;&gt;Powrót do spisu treści &lt;/a&gt;&lt;/h3&gt;.
        /// </summary>
        public static string h3 {
            get {
                return ResourceManager.GetString("h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=utf-8&quot; &gt;
        ///&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/styl.css&quot;&gt;
        ///&lt;title&gt;Dokumentacha High Level Design (HLD) dla projektu ^@^  wygenerowano  ^@^&lt;/title&gt;
        ///&lt;/head&gt;
        ///.
        /// </summary>
        public static string naglowek {
            get {
                return ResourceManager.GetString("naglowek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///Celem niniejszego dokumentu jest przedstawienie sposobu realizacji Wymagań Biznesowych dla projektu zawartych w dokumencie Concept Paper. Na opis sposób realizacji składają się następujące główne elementy:&lt;br&gt;
        ///1.	odniesienie do wymagań biznesowych&lt;br&gt;
        ///2.	zarys koncepcji rozwiązania&lt;br&gt;
        ///3.	opis architektury rozwiązania wraz z dekompozycją koniecznych zmian funkcjonalnych na poszczególne systemy&lt;br&gt;
        ///4.	opis koniecznych do wykonania zmian w poszczególnych systemach&lt;br&gt;
        ///5.	opis zmian koniecznych z pun [rest of string was truncated]&quot;;.
        /// </summary>
        public static string rozdzial1 {
            get {
                return ResourceManager.GetString("rozdzial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window.onload = function() {
        ///var elements = document.getElementsByTagName(&apos;*&apos;),
        ///i;
        ///for (i in elements) {
        ///if (elements[i].hasAttribute &amp;&amp; elements[i].hasAttribute(&apos;data-include&apos;)) {
        ///fragment(elements[i], elements[i].getAttribute(&apos;data-include&apos;));
        ///}
        ///}
        ///function fragment(el, url) {
        ///var localTest = /^(?:file):/,
        ///xmlhttp = new XMLHttpRequest(),
        ///status = 0;
        ///
        ///xmlhttp.onreadystatechange = function() {
        ////* if we are on a local protocol, and we have response text, we&apos;ll assume
        ///* things were sucessful */        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string skrypt {
            get {
                return ResourceManager.GetString("skrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        public static string stopka {
            get {
                return ResourceManager.GetString("stopka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul{list-style-type:square;}
        ///h1.tytul{color:#CC3399;font-size:40px;font-family:Arial, Helvetica, sans-serif;text-align:center;}
        ///h1:target{ padding-top: 50px; }
        ///h1{color:#CC3399;font-family:Arial, Helvetica, sans-serif;font-size:30px;}
        ///h2{color:black;font-family:Arial, Helvetica, sans-serif;font-size:20px;}
        ///h3{color:black;font-family:Arial, Helvetica, sans-serif;font-size:15px;}
        ///p{font-family:&quot;Times New Roman&quot;, Times, serif;}
        ///a.spis1{color:#CC3399;font-size:18px;font-family:Arial, Helvetica, sans-serif [rest of string was truncated]&quot;;.
        /// </summary>
        public static string styl {
            get {
                return ResourceManager.GetString("styl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Szablon {
            get {
                object obj = ResourceManager.GetObject("Szablon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;img src=&apos;^@^img/logo.png&apos;&gt;
        /// &lt;h1 class=\&quot;tytul\&quot;&gt;High Level Design dla projektu &lt;br&gt; ^@^ &lt;/h1&gt;&lt;br&gt;
        /// &lt;ul&gt;
        /// &lt;li&gt; Autor: ^@^&lt;/li&gt;
        /// &lt;li&gt; Data generowania ^@^ &lt;/li&gt;
        /// &lt;li&gt; Wersja generatora: 0.1, wszelkie uwagi dotyczące generatora HLD kierować na adres Krzysztof.Zagawa@exteranal.t-mobile.pl &lt;/li&gt;
        /// &lt;/ul&gt;.
        /// </summary>
        public static string wstep {
            get {
                return ResourceManager.GetString("wstep", resourceCulture);
            }
        }
    }
}
